redis:
  image: redis
  ports:
    - 6379:6379
web:
  build: .
  dockerfile: Dockerfile
  links:
    - redis
  ports:
    - 5000:5000
worker:
  build: .
  dockerfile: Dockerfile-worker
  links:
    - redis